apiVersion: v1
kind: ConfigMap
metadata:
  name: dotnet-config
  namespace: dotnet-namespace
  labels:
    app: dotnet-app
    environment: production
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  # Database configuration
  ConnectionStrings__DefaultConnection: "Data Source=/app/data/NORTHWND.sqlite"
  # Application settings
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft: "Warning"
  # Security settings
  AllowedHosts: "*"
  # Custom application settings
  WebGoat__Environment: "production"
  WebGoat__Debug: "false"
