apiVersion: v1
kind: ServiceAccount
metadata:
  name: dotnet-service-account
  namespace: dotnet-namespace
  labels:
    app: dotnet-app
    environment: production
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dotnet-role
  namespace: dotnet-namespace
  labels:
    app: dotnet-app
    environment: production
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dotnet-role-binding
  namespace: dotnet-namespace
  labels:
    app: dotnet-app
    environment: production
subjects:
- kind: ServiceAccount
  name: dotnet-service-account
  namespace: dotnet-namespace
roleRef:
  kind: Role
  name: dotnet-role
  apiGroup: rbac.authorization.k8s.io
