apiVersion: v1
kind: Secret
metadata:
  name: dotnet-secrets
  namespace: dotnet-namespace
  labels:
    app: dotnet-app
    environment: production
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  # Use: echo -n "your-secret-value" | base64
  database-password: cGFzc3dvcmQ=  # "password" - replace with actual password
  jwt-secret: bXktand0LXNlY3JldC1rZXk=  # "my-jwt-secret-key" - replace with actual JWT key
  api-key: YXBpLWtleS12YWx1ZQ==  # "api-key-value" - replace with actual API key
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dotnet-security-config
  namespace: dotnet-namespace
  labels:
    app: dotnet-app
    environment: production
data:
  # Security headers configuration
  security-headers.json: |
    {
      "SecurityHeaders": {
        "ContentSecurityPolicy": "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; media-src 'self'; object-src 'none'; child-src 'self'; frame-ancestors 'none'; form-action 'self'; base-uri 'self'",
        "StrictTransportSecurity": "max-age=31536000; includeSubDomains",
        "XContentTypeOptions": "nosniff",
        "XFrameOptions": "DENY",
        "XSSProtection": "1; mode=block",
        "ReferrerPolicy": "strict-origin-when-cross-origin"
      }
    }
